//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDream.Tables {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectDream.Tables.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string AButtonDefault {
            get {
                return ResourceManager.GetString("AButtonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string AButtonDuel {
            get {
                return ResourceManager.GetString("AButtonDuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump / Shoot.
        /// </summary>
        internal static string AButtonFT {
            get {
                return ResourceManager.GetString("AButtonFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        internal static string AButtonLumberjack {
            get {
                return ResourceManager.GetString("AButtonLumberjack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string BackButtonDefault {
            get {
                return ResourceManager.GetString("BackButtonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string BButtonDefault {
            get {
                return ResourceManager.GetString("BButtonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string BButtonDuel {
            get {
                return ResourceManager.GetString("BButtonDuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Attack.
        /// </summary>
        internal static string BButtonFT {
            get {
                return ResourceManager.GetString("BButtonFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minigames.
        /// </summary>
        internal static string ChooseMode {
            get {
                return ResourceManager.GetString("ChooseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current culture: {0}.
        /// </summary>
        internal static string CurrentLocale {
            get {
                return ResourceManager.GetString("CurrentLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Stranded on a melting iceberg 
        ///and forced to spin uncontrollably, 
        ///you must survive this wizard`s
        ///test. Bump your so called friends 
        ///off the island to be the last player 
        ///standing. Work as a team to win.
        ///
        ///Press &quot;A&quot; to start..
        /// </summary>
        internal static string DescriptionBB {
            get {
                return ResourceManager.GetString("DescriptionBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      The final test is for the two best.
        ///Fight the pull of the sinking sands 
        ///by pushing the designated button
        ///repeatedly. Watch your opponent 
        ///sink into the abyss, making you the 
        ///ultimate champion!
        ///
        ///Press &quot;A&quot; to start..
        /// </summary>
        internal static string DescriptionDuel {
            get {
                return ResourceManager.GetString("DescriptionDuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      One will throw fire, while the
        ///others flee in this wizard&apos;s test.
        ///Setting three ablaze will allow
        ///for one to be the best.
        ///
        ///Press &quot;A&quot; to start..
        /// </summary>
        internal static string DescriptionFT {
            get {
                return ResourceManager.GetString("DescriptionFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Race through the wizard&apos;s 
        ///dark forest and secure your
        ///place in the living. Careful, the
        ///wizard has placed traps you must
        ///duck under, jump over or chop 
        ///through or be slowed down.
        ///
        ///Press &quot;A&quot; to start..
        /// </summary>
        internal static string DescriptionLumberjack {
            get {
                return ResourceManager.GetString("DescriptionLumberjack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string DesriptionDefault {
            get {
                return ResourceManager.GetString("DesriptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string DirectionalPadBB {
            get {
                return ResourceManager.GetString("DirectionalPadBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string DirectionalPadDefault {
            get {
                return ResourceManager.GetString("DirectionalPadDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string DirectionalPadFT {
            get {
                return ResourceManager.GetString("DirectionalPadFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide.
        /// </summary>
        internal static string DirectionalPadLumberjack {
            get {
                return ResourceManager.GetString("DirectionalPadLumberjack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Game.
        /// </summary>
        internal static string ExitGame {
            get {
                return ResourceManager.GetString("ExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string LeftBumperDefault {
            get {
                return ResourceManager.GetString("LeftBumperDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string LeftStickDefault {
            get {
                return ResourceManager.GetString("LeftStickDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string LeftStickFT {
            get {
                return ResourceManager.GetString("LeftStickFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string LeftTriggerDefault {
            get {
                return ResourceManager.GetString("LeftTriggerDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;A&quot; to continue.
        /// </summary>
        internal static string PressAContinue {
            get {
                return ResourceManager.GetString("PressAContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string RightBumperDefault {
            get {
                return ResourceManager.GetString("RightBumperDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string RightStickDefault {
            get {
                return ResourceManager.GetString("RightStickDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string RightTriggerDefault {
            get {
                return ResourceManager.GetString("RightTriggerDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores.
        /// </summary>
        internal static string ScoreTitle {
            get {
                return ResourceManager.GetString("ScoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string StartButtonDefault {
            get {
                return ResourceManager.GetString("StartButtonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story Mode.
        /// </summary>
        internal static string StoryMode {
            get {
                return ResourceManager.GetString("StoryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bumper Balls.
        /// </summary>
        internal static string TitleBB {
            get {
                return ResourceManager.GetString("TitleBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string TitleDefault {
            get {
                return ResourceManager.GetString("TitleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dueling Dunes.
        /// </summary>
        internal static string TitleDuel {
            get {
                return ResourceManager.GetString("TitleDuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fireball Tactics.
        /// </summary>
        internal static string TitleFT {
            get {
                return ResourceManager.GetString("TitleFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lumberjack Bustle.
        /// </summary>
        internal static string TitleLumberjack {
            get {
                return ResourceManager.GetString("TitleLumberjack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string XBoxButtonDefault {
            get {
                return ResourceManager.GetString("XBoxButtonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string XButtonDefault {
            get {
                return ResourceManager.GetString("XButtonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string XButtonDuel {
            get {
                return ResourceManager.GetString("XButtonDuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duck.
        /// </summary>
        internal static string XButtonFT {
            get {
                return ResourceManager.GetString("XButtonFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slash.
        /// </summary>
        internal static string XButtonLumberjack {
            get {
                return ResourceManager.GetString("XButtonLumberjack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string YButtonDefault {
            get {
                return ResourceManager.GetString("YButtonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string YButtonDuel {
            get {
                return ResourceManager.GetString("YButtonDuel", resourceCulture);
            }
        }
    }
}
